# Limpieza de los nuevos datos del Web Scraping

1. Importación de librerías

In [1]:
import pandas as pd    # Para manejar datos en tablas (DataFrames)
from pathlib import Path  # Para manejar rutas de archivos
import os              # Para funciones del sistema operativo
import re              # Para expresiones regulares

C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

2. Carga del dataset de reseñas

In [3]:
# Mostrar el directorio donde estamos trabajando
print("Directorio de trabajo actual:")
print(os.getcwd())

# Construir la ruta al archivo usando pathlib
ruta_final = proyecto / "data" / "raw"  # Carpeta donde están los datos crudos
archivo = "reseñas_costa_rica_nuevas.csv"  # Nombre del archivo generado en el Notebook 1

# Cargar el CSV en un DataFrame de pandas
df = pd.read_csv(ruta_final / archivo)

# Confirmar que el dataset se cargó correctamente
print("Dataset cargado")

# Mostrar dimensiones del dataset
print("Dimensiones:", df.shape)

# Mostrar los nombres de todas las columnas
print("Columnas:", df.columns.tolist())

# Mostrar las primeras 3 filas
df.head(3)

Directorio de trabajo actual:
C:\ProyectoIIMT\An-lisis-Sem-ntico-de-Rese-as-Tur-sticas-de-Costa-Rica-\notebooks
Dataset cargado
Dimensiones: (9948, 10)
Columnas: ['lugar', 'place_id', 'autor', 'calificacion', 'fecha_relativa', 'fecha_exacta', 'idioma_original', 'texto_original', 'fuente', 'fecha_recopilacion']

,lugar,place_id,autor,calificacion,fecha_relativa,fecha_exacta,idioma_original,texto_original,fuente,fecha_recopilacion
0,Hotel Arenal Montechiari,ChIJHaldU4oMoI8RHPCMRU6CEro,Tim Shaw,5,a month ago,2026-06-06T22:32:44.312671730Z,en,Absolutely stunning spot. The grounds are gorg...,google_places_api,2026-07-27T20:33:12.610824
1,Hotel Arenal Montechiari,ChIJHaldU4oMoI8RHPCMRU6CEro,K Love,5,7 months ago,2025-12-29T19:45:02.406352074Z,en,We stayed here for three nights with family an...,google_places_api,2026-07-27T20:33:12.617851
2,Hotel Arenal Montechiari,ChIJHaldU4oMoI8RHPCMRU6CEro,EL Broverlander,5,3 months ago,2026-04-10T17:24:14.359674268Z,en,We enjoyed a wonderful 3 bed cabin on the quie...,google_places_api,2026-07-27T20:33:12.617851

3. Selección de columnas relevantes

In [4]:
# Definir las columnas que nos interesan para el análisis
columnas_deseadas = [
    "texto_original",    # Texto de la reseña
    "calificacion",      # Puntuación
    "fuente",            # Fuente de datos ("google_places_api")
    "lugar",             # Nombre del establecimiento
    "fecha_exacta",      # Fecha de publicación de la reseña
    "idioma_original"    # Idioma en que está escrita la reseña
]

# Filtrar solo las columnas que existen en el DataFrame
columnas_presentes = [c for c in columnas_deseadas if c in df.columns]

# Crear un nuevo DataFrame solo con las columnas seleccionadas
df = df[columnas_presentes].copy()

# Mostrar las columnas que se conservaron
print("Columnas conservadas:")
print(df.columns.tolist())

# Mostrar dimensiones del nuevo DataFrame
print(df.shape)

# Mostrar primeras filas para verificar la selección
df.head()

Columnas conservadas:
['texto_original', 'calificacion', 'fuente', 'lugar', 'fecha_exacta', 'idioma_original']
(9948, 6)

,texto_original,calificacion,fuente,lugar,fecha_exacta,idioma_original
0,Absolutely stunning spot. The grounds are gorg...,5,google_places_api,Hotel Arenal Montechiari,2026-06-06T22:32:44.312671730Z,en
1,We stayed here for three nights with family an...,5,google_places_api,Hotel Arenal Montechiari,2025-12-29T19:45:02.406352074Z,en
2,We enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,Hotel Arenal Montechiari,2026-04-10T17:24:14.359674268Z,en
3,I recently stayed at Hotel Montechiari in La F...,3,google_places_api,Hotel Arenal Montechiari,2025-11-29T02:56:35.840358616Z,en
4,We stayed two nights at Arenal Montechiari. Th...,5,google_places_api,Hotel Arenal Montechiari,2025-12-16T18:14:57.243736508Z,en

4. Eliminación de registros duplicados

In [5]:
# Identificar filas duplicadas
duplicados = df.duplicated()

# Mostrar cuántos duplicados se encontraron
print("Duplicados encontrados:", duplicados.sum())

# Eliminar las filas duplicadas
df = df.drop_duplicates()

# Mostrar el nuevo tamaño del dataset después de eliminar duplicados
print("Nuevo tamaño:", df.shape)

Duplicados encontrados: 0
Nuevo tamaño: (9948, 6)

5. Eliminación de filas completamente vacías

In [6]:
# Detectar filas donde todas las columnas están vacía
filas_vacias = df.isnull().all(axis=1)

# Mostrar cuántas filas completamente vacías se encontraron
print("Filas completamente vacías:", filas_vacias.sum())

# Eliminar esas filas
df = df[~filas_vacias].copy()

# Mostrar el nuevo tamaño del dataset
print(df.shape)

Filas completamente vacías: 0
(9948, 6)

6. Renombrado de columnas para facilitar el análisis

In [7]:
# Diccionario para renombrar columnas
mapeo = {
    "texto_original": "reseña",      # Texto de la reseña
    "calificacion": "calificación",  # Puntuación
    "fuente": "fuente",              # Fuente de datos
    "lugar": "nombre",               # Nombre del establecimiento
    "fecha_exacta": "fecha",         # Fecha de publicación
    "idioma_original": "idioma"      # Idioma de la reseña
}

# Aplicar el renombrado directamente al DataFrame
df.rename(columns=mapeo, inplace=True)

# Mostrar las columnas actualizadas
print("Columnas renombradas:")
print(df.columns.tolist())

# Mostrar primeras filas para verificar el cambio
df.head()

['reseña', 'calificación', 'fuente', 'nombre', 'fecha', 'idioma']

,reseña,calificación,fuente,nombre,fecha,idioma
0,Absolutely stunning spot. The grounds are gorg...,5,google_places_api,Hotel Arenal Montechiari,2026-06-06T22:32:44.312671730Z,en
1,We stayed here for three nights with family an...,5,google_places_api,Hotel Arenal Montechiari,2025-12-29T19:45:02.406352074Z,en
2,We enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,Hotel Arenal Montechiari,2026-04-10T17:24:14.359674268Z,en
3,I recently stayed at Hotel Montechiari in La F...,3,google_places_api,Hotel Arenal Montechiari,2025-11-29T02:56:35.840358616Z,en
4,We stayed two nights at Arenal Montechiari. Th...,5,google_places_api,Hotel Arenal Montechiari,2025-12-16T18:14:57.243736508Z,en

7. Conversión de texto a minúsculas

In [8]:
# Aplicar .lower() a todas las celdas que sean strings (texto)
# Si la celda no es string (ej. número, fecha), se deja igual
df = df.map(lambda x: x.lower() if isinstance(x, str) else x)

# Confirmar la conversión
print("Texto convertido a minúsculas.")

# Mostrar primeras filas para verificar el cambio
df.head()

Texto convertido a minúsculas.

,reseña,calificación,fuente,nombre,fecha,idioma
0,absolutely stunning spot. the grounds are gorg...,5,google_places_api,hotel arenal montechiari,2026-06-06t22:32:44.312671730z,en
1,we stayed here for three nights with family an...,5,google_places_api,hotel arenal montechiari,2025-12-29t19:45:02.406352074z,en
2,we enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,hotel arenal montechiari,2026-04-10t17:24:14.359674268z,en
3,i recently stayed at hotel montechiari in la f...,3,google_places_api,hotel arenal montechiari,2025-11-29t02:56:35.840358616z,en
4,we stayed two nights at arenal montechiari. th...,5,google_places_api,hotel arenal montechiari,2025-12-16t18:14:57.243736508z,en

8. Conversión de fechas a formato datetime

In [10]:
# Convertir la columna "fecha" a formato datetime (fecha/hora)
# format="mixed": detecta automáticamente diferentes formatos de fecha
# errors="coerce": si no puede convertir, pone NaN (en lugar de error)
# .dt.date: extrae solo la fecha (sin la hora)
df["fecha"] = pd.to_datetime(
    df["fecha"],
    format="mixed",
    errors="coerce"
).dt.date

# Mostrar primeras filas para verificar la conversión
df.head()

,reseña,calificación,fuente,nombre,fecha,idioma
0,absolutely stunning spot. the grounds are gorg...,5,google_places_api,hotel arenal montechiari,2026-06-06,en
1,we stayed here for three nights with family an...,5,google_places_api,hotel arenal montechiari,2025-12-29,en
2,we enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,hotel arenal montechiari,2026-04-10,en
3,i recently stayed at hotel montechiari in la f...,3,google_places_api,hotel arenal montechiari,2025-11-29,en
4,we stayed two nights at arenal montechiari. th...,5,google_places_api,hotel arenal montechiari,2025-12-16,en

9. Eliminación de reseñas vacías o sin texto

In [11]:
# Detectar reseñas que están vacías o que solo tienen espacios
condicion = df["reseña"].isna() | (df["reseña"].str.strip() == "")

# Mostrar cuántas reseñas vacías se encontraron
print("Reseñas vacías:", condicion.sum())

# Eliminar esas filas
df = df[~condicion].copy()

# Mostrar el nuevo tamaño del dataset
print(df.shape)

Reseñas vacías: 139
(9809, 6)

10. Limpieza de texto (eliminación de caracteres especiales)

In [12]:
# Función para limpiar texto eliminando caracteres no deseados
def limpiar(texto):
    # Si no es texto, devolver string vacío
    if not isinstance(texto, str):
        return ""

    # Reemplazar cualquier caracter que NO sea:
    # - Letras (a-z, A-Z, incluyendo acentos y ñ)
    # - Números (0-9)
    # - Espacios (\s)
    # Por un espacio en blanco
    texto = re.sub(r"[^a-zA-ZáéíóúÁÉÍÓÚñÑüÜ0-9\s]", " ", texto)

    # Reemplazar múltiples espacios por uno solo
    texto = re.sub(r"\s+", " ", texto)

    # Eliminar espacios al inicio y final
    return texto.strip()

# Aplicar la limpieza a las columnas de texto
df["reseña"] = df["reseña"].apply(limpiar)  # Limpiar reseñas
df["nombre"] = df["nombre"].apply(limpiar)  # Limpiar nombres

# Confirmar la limpieza
print("Caracteres especiales eliminados.")

# Mostrar primeras filas para verificar el cambio
df.head()

Caracteres especiales eliminados.

,reseña,calificación,fuente,nombre,fecha,idioma
0,absolutely stunning spot the grounds are gorge...,5,google_places_api,hotel arenal montechiari,2026-06-06,en
1,we stayed here for three nights with family an...,5,google_places_api,hotel arenal montechiari,2025-12-29,en
2,we enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,hotel arenal montechiari,2026-04-10,en
3,i recently stayed at hotel montechiari in la f...,3,google_places_api,hotel arenal montechiari,2025-11-29,en
4,we stayed two nights at arenal montechiari the...,5,google_places_api,hotel arenal montechiari,2025-12-16,en

11. Eliminación de reseñas vacías después de la limpieza

In [13]:
# Detectar reseñas que quedaron vacías después de la limpieza
vacias = (df["reseña"] == "") | (df["reseña"].isna())

# Mostrar cuántas reseñas vacías se encontraron
print(vacias.sum())

# Eliminar esas filas
df = df[~vacias].copy()

# Mostrar el nuevo tamaño del dataset
print(df.shape)

3
(9806, 6)

12. Separación de reseñas por idioma (español e inglés)

In [14]:
# Filtrar reseñas en español
df_es = df[df["idioma"] == "es"].copy()

# Filtrar reseñas en inglés
df_en = df[df["idioma"] == "en"].copy()

# Mostrar cuántas reseñas hay en cada idioma
print("Español:", len(df_es))
print("Inglés:", len(df_en))

Español: 968
Inglés: 8741

13. Muestreo de reseñas en inglés para equilibrio

In [15]:
# Tomar una muestra aleatoria de 1000 reseñas en inglés
# Esto ayuda a equilibrar el dataset si hay muchas más reseñas en inglés que en español
df_en = df_en.sample(
    n=1000,          # Número de reseñas a seleccionar
    random_state=42  # Semilla fija para que el resultado sea reproducible
)

# Mostrar el nuevo tamaño del dataset en inglés
print(df_en.shape)

(1000, 6)

14. Traducción de reseñas de inglés a español

In [16]:
# Importar el traductor de Google (deep_translator)
from deep_translator import GoogleTranslator

# Crear una instancia del traductor (de inglés a español)
traductor = GoogleTranslator(source="en", target="es")

# Traducir todas las reseñas en inglés al español
df_en["reseña"] = df_en["reseña"].apply(
    lambda x: traductor.translate(x)
)

#Para instalar la librería ejecutar en terminal: pip install deep-translator

15. Unión de reseñas en español y traducidas

In [17]:
# Concatenar los DataFrames de español e inglés traducido
df = pd.concat(
    [df_es, df_en],        # Lista de DataFrames a unir
    ignore_index=True      # Reinicia los índices
)

# Mostrar el tamaño total del dataset combinado
print(df.shape)

(1968, 6)

 16. Eliminación de columna de idioma

In [18]:
# Eliminar la columna "idioma" ya que todas las reseñas están ahora en español
df.drop(columns=["idioma"], inplace=True)

# Mostrar primeras filas para verificar que se eliminó la columna
df.head()

,reseña,calificación,fuente,nombre,fecha
0,excelente lugar camas aire acondicinado todo n...,5,google_places_api,sky hostel fortuna,2026-03-30
1,la cabina muy bien equipada y limpia pero la s...,1,google_places_api,cabinas guayabón,2026-07-02
2,definitivamente un lugar muy tranquilo para de...,4,google_places_api,cabinas guayabón,2025-10-21
3,una experiencia agradable con ubicación muy bu...,4,google_places_api,cabinas guayabón,2026-01-18
4,sobre las aguas termales recomendado están sep...,4,google_places_api,cabinas las termalitas,2026-03-17

17. Conversión de calificaciones a números enteros

In [19]:
# Convertir la columna "calificación" a formato numérico
# errors="coerce": si no puede convertir, lo deja como NaN
# astype("Int64"): lo convierte a números enteros
df["calificación"] = pd.to_numeric(
    df["calificación"],
    errors="coerce"
).astype("Int64")

# Mostrar primeras filas para verificar el cambio
df.head()

,reseña,calificación,fuente,nombre,fecha
0,excelente lugar camas aire acondicinado todo n...,5,google_places_api,sky hostel fortuna,2026-03-30
1,la cabina muy bien equipada y limpia pero la s...,1,google_places_api,cabinas guayabón,2026-07-02
2,definitivamente un lugar muy tranquilo para de...,4,google_places_api,cabinas guayabón,2025-10-21
3,una experiencia agradable con ubicación muy bu...,4,google_places_api,cabinas guayabón,2026-01-18
4,sobre las aguas termales recomendado están sep...,4,google_places_api,cabinas las termalitas,2026-03-17

18. Guardado del dataset limpio

In [20]:
# Definir la ruta donde se guardará el archivo limpio
ruta_salida = proyecto / "data" / "processed" / "reseñas_clean.csv"

# Crear la carpeta donde se guardará
ruta_salida.parent.mkdir(
    parents=True,   # Crea las carpetas intermedias si no existen
    exist_ok=True   # No lanza error si la carpeta ya existe
)

# Guardar el DataFrame en formato CSV
df.to_csv(
    ruta_salida,    # Ruta completa donde se guardará
    index=False     # No incluir el índice como columna
)

# Confirmar que se guardó correctamente
print("Archivo guardado correctamente.")

# Mostrar dimensiones del dataset guardado
print(df.shape)

Archivo guardado correctamente.
(1968, 5)

19. Guardado del dataset limpio (versión final P2)

In [21]:
# Ruta donde se guardará el archivo
ruta_salida = proyecto / "data" / "processed" / "reseñas_clean_P2.csv"

# Crear la carpeta si no existe
ruta_salida.parent.mkdir(parents=True, exist_ok=True)

# Guardar el CSV
df.to_csv(ruta_salida, index=False)

# Confirmar la ubicación del archivo
print("Archivo guardado en:")
print(ruta_salida)

Archivo guardado en:
C:\ProyectoIIMT\An-lisis-Sem-ntico-de-Rese-as-Tur-sticas-de-Costa-Rica-\data\processed\reseñas_clean_P2.csv