In [1]:
#Librerías
import pandas as pd
from pathlib import Path
import os
import re

C:\Users\ferna\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
from pathlib import Path
import os

# Carpeta raíz del proyecto
proyecto = Path.cwd().parent

print("Proyecto:")
print(proyecto)

Proyecto:
C:\ProyectoIIMT\An-lisis-Sem-ntico-de-Rese-as-Tur-sticas-de-Costa-Rica-

In [3]:
#Carga del dataset
print("Directorio de trabajo actual:")
print(os.getcwd())

ruta_final = proyecto / "data" / "raw"
archivo = "reseñas_costa_rica_nuevas.csv"

df = pd.read_csv(ruta_final / archivo)

print("Dataset cargado")
print("Dimensiones:", df.shape)
print("Columnas:", df.columns.tolist())

df.head(3)

Directorio de trabajo actual:
C:\ProyectoIIMT\An-lisis-Sem-ntico-de-Rese-as-Tur-sticas-de-Costa-Rica-\notebooks
Dataset cargado
Dimensiones: (9948, 10)
Columnas: ['lugar', 'place_id', 'autor', 'calificacion', 'fecha_relativa', 'fecha_exacta', 'idioma_original', 'texto_original', 'fuente', 'fecha_recopilacion']

,lugar,place_id,autor,calificacion,fecha_relativa,fecha_exacta,idioma_original,texto_original,fuente,fecha_recopilacion
0,Hotel Arenal Montechiari,ChIJHaldU4oMoI8RHPCMRU6CEro,Tim Shaw,5,a month ago,2026-06-06T22:32:44.312671730Z,en,Absolutely stunning spot. The grounds are gorg...,google_places_api,2026-07-27T20:33:12.610824
1,Hotel Arenal Montechiari,ChIJHaldU4oMoI8RHPCMRU6CEro,K Love,5,7 months ago,2025-12-29T19:45:02.406352074Z,en,We stayed here for three nights with family an...,google_places_api,2026-07-27T20:33:12.617851
2,Hotel Arenal Montechiari,ChIJHaldU4oMoI8RHPCMRU6CEro,EL Broverlander,5,3 months ago,2026-04-10T17:24:14.359674268Z,en,We enjoyed a wonderful 3 bed cabin on the quie...,google_places_api,2026-07-27T20:33:12.617851

In [4]:
columnas_deseadas = [
    "texto_original",
    "calificacion",
    "fuente",
    "lugar",
    "fecha_exacta",
    "idioma_original"
]

columnas_presentes = [c for c in columnas_deseadas if c in df.columns]

df = df[columnas_presentes].copy()

print("Columnas conservadas:")
print(df.columns.tolist())

print(df.shape)

df.head()

Columnas conservadas:
['texto_original', 'calificacion', 'fuente', 'lugar', 'fecha_exacta', 'idioma_original']
(9948, 6)

,texto_original,calificacion,fuente,lugar,fecha_exacta,idioma_original
0,Absolutely stunning spot. The grounds are gorg...,5,google_places_api,Hotel Arenal Montechiari,2026-06-06T22:32:44.312671730Z,en
1,We stayed here for three nights with family an...,5,google_places_api,Hotel Arenal Montechiari,2025-12-29T19:45:02.406352074Z,en
2,We enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,Hotel Arenal Montechiari,2026-04-10T17:24:14.359674268Z,en
3,I recently stayed at Hotel Montechiari in La F...,3,google_places_api,Hotel Arenal Montechiari,2025-11-29T02:56:35.840358616Z,en
4,We stayed two nights at Arenal Montechiari. Th...,5,google_places_api,Hotel Arenal Montechiari,2025-12-16T18:14:57.243736508Z,en

In [5]:
duplicados = df.duplicated()

print("Duplicados encontrados:", duplicados.sum())

df = df.drop_duplicates()

print("Nuevo tamaño:", df.shape)

Duplicados encontrados: 0
Nuevo tamaño: (9948, 6)

In [6]:
filas_vacias = df.isnull().all(axis=1)

print("Filas completamente vacías:", filas_vacias.sum())

df = df[~filas_vacias].copy()

print(df.shape)

Filas completamente vacías: 0
(9948, 6)

In [7]:
mapeo = {
    "texto_original":"reseña",
    "calificacion":"calificación",
    "fuente":"fuente",
    "lugar":"nombre",
    "fecha_exacta":"fecha",
    "idioma_original":"idioma"
}

df.rename(columns=mapeo,inplace=True)

print(df.columns.tolist())

df.head()

['reseña', 'calificación', 'fuente', 'nombre', 'fecha', 'idioma']

,reseña,calificación,fuente,nombre,fecha,idioma
0,Absolutely stunning spot. The grounds are gorg...,5,google_places_api,Hotel Arenal Montechiari,2026-06-06T22:32:44.312671730Z,en
1,We stayed here for three nights with family an...,5,google_places_api,Hotel Arenal Montechiari,2025-12-29T19:45:02.406352074Z,en
2,We enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,Hotel Arenal Montechiari,2026-04-10T17:24:14.359674268Z,en
3,I recently stayed at Hotel Montechiari in La F...,3,google_places_api,Hotel Arenal Montechiari,2025-11-29T02:56:35.840358616Z,en
4,We stayed two nights at Arenal Montechiari. Th...,5,google_places_api,Hotel Arenal Montechiari,2025-12-16T18:14:57.243736508Z,en

In [8]:
df = df.map(lambda x: x.lower() if isinstance(x,str) else x)

print("Texto convertido a minúsculas.")

df.head()

Texto convertido a minúsculas.

,reseña,calificación,fuente,nombre,fecha,idioma
0,absolutely stunning spot. the grounds are gorg...,5,google_places_api,hotel arenal montechiari,2026-06-06t22:32:44.312671730z,en
1,we stayed here for three nights with family an...,5,google_places_api,hotel arenal montechiari,2025-12-29t19:45:02.406352074z,en
2,we enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,hotel arenal montechiari,2026-04-10t17:24:14.359674268z,en
3,i recently stayed at hotel montechiari in la f...,3,google_places_api,hotel arenal montechiari,2025-11-29t02:56:35.840358616z,en
4,we stayed two nights at arenal montechiari. th...,5,google_places_api,hotel arenal montechiari,2025-12-16t18:14:57.243736508z,en

In [10]:
df["fecha"] = pd.to_datetime(
    df["fecha"],
    format="mixed",
    errors="coerce"
).dt.date

df.head()

,reseña,calificación,fuente,nombre,fecha,idioma
0,absolutely stunning spot. the grounds are gorg...,5,google_places_api,hotel arenal montechiari,2026-06-06,en
1,we stayed here for three nights with family an...,5,google_places_api,hotel arenal montechiari,2025-12-29,en
2,we enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,hotel arenal montechiari,2026-04-10,en
3,i recently stayed at hotel montechiari in la f...,3,google_places_api,hotel arenal montechiari,2025-11-29,en
4,we stayed two nights at arenal montechiari. th...,5,google_places_api,hotel arenal montechiari,2025-12-16,en

In [11]:
condicion = df["reseña"].isna() | (df["reseña"].str.strip()=="")

print("Reseñas vacías:", condicion.sum())

df = df[~condicion].copy()

print(df.shape)

Reseñas vacías: 139
(9809, 6)

In [12]:
def limpiar(texto):

    if not isinstance(texto,str):
        return ""

    texto = re.sub(r"[^a-zA-ZáéíóúÁÉÍÓÚñÑüÜ0-9\s]"," ",texto)

    texto = re.sub(r"\s+"," ",texto)

    return texto.strip()

df["reseña"] = df["reseña"].apply(limpiar)

df["nombre"] = df["nombre"].apply(limpiar)

print("Caracteres especiales eliminados.")

df.head()

Caracteres especiales eliminados.

,reseña,calificación,fuente,nombre,fecha,idioma
0,absolutely stunning spot the grounds are gorge...,5,google_places_api,hotel arenal montechiari,2026-06-06,en
1,we stayed here for three nights with family an...,5,google_places_api,hotel arenal montechiari,2025-12-29,en
2,we enjoyed a wonderful 3 bed cabin on the quie...,5,google_places_api,hotel arenal montechiari,2026-04-10,en
3,i recently stayed at hotel montechiari in la f...,3,google_places_api,hotel arenal montechiari,2025-11-29,en
4,we stayed two nights at arenal montechiari the...,5,google_places_api,hotel arenal montechiari,2025-12-16,en

In [13]:
vacias = (df["reseña"]=="") | (df["reseña"].isna())

print(vacias.sum())

df = df[~vacias].copy()

print(df.shape)

3
(9806, 6)

In [14]:
df_es = df[df["idioma"]=="es"].copy()

df_en = df[df["idioma"]=="en"].copy()

print("Español:",len(df_es))
print("Inglés:",len(df_en))

Español: 968
Inglés: 8741

In [15]:
df_en = df_en.sample(
    n=1000,
    random_state=42
)

print(df_en.shape)

(1000, 6)

In [16]:
from deep_translator import GoogleTranslator

traductor = GoogleTranslator(source="en",target="es")

df_en["reseña"] = df_en["reseña"].apply(
    lambda x: traductor.translate(x)
) #instalar libreria de traducción

In [17]:
df = pd.concat(
    [df_es,df_en],
    ignore_index=True
)

print(df.shape)

(1968, 6)

In [18]:
df.drop(columns=["idioma"],inplace=True)

df.head()

,reseña,calificación,fuente,nombre,fecha
0,excelente lugar camas aire acondicinado todo n...,5,google_places_api,sky hostel fortuna,2026-03-30
1,la cabina muy bien equipada y limpia pero la s...,1,google_places_api,cabinas guayabón,2026-07-02
2,definitivamente un lugar muy tranquilo para de...,4,google_places_api,cabinas guayabón,2025-10-21
3,una experiencia agradable con ubicación muy bu...,4,google_places_api,cabinas guayabón,2026-01-18
4,sobre las aguas termales recomendado están sep...,4,google_places_api,cabinas las termalitas,2026-03-17

In [19]:
df["calificación"] = pd.to_numeric(
    df["calificación"],
    errors="coerce"
).astype("Int64")

df.head()

,reseña,calificación,fuente,nombre,fecha
0,excelente lugar camas aire acondicinado todo n...,5,google_places_api,sky hostel fortuna,2026-03-30
1,la cabina muy bien equipada y limpia pero la s...,1,google_places_api,cabinas guayabón,2026-07-02
2,definitivamente un lugar muy tranquilo para de...,4,google_places_api,cabinas guayabón,2025-10-21
3,una experiencia agradable con ubicación muy bu...,4,google_places_api,cabinas guayabón,2026-01-18
4,sobre las aguas termales recomendado están sep...,4,google_places_api,cabinas las termalitas,2026-03-17

In [20]:
ruta_salida = proyecto / "data" / "processed" / "reseñas_clean.csv"

ruta_salida.parent.mkdir(
    parents=True,
    exist_ok=True
)

df.to_csv(
    ruta_salida,
    index=False
)

print("Archivo guardado correctamente.")
print(df.shape)

Archivo guardado correctamente.
(1968, 5)

In [21]:
# Ruta donde se guardará el archivo
ruta_salida = proyecto / "data" / "processed" / "reseñas_clean_P2.csv"

# Crear la carpeta si no existe
ruta_salida.parent.mkdir(parents=True, exist_ok=True)

# Guardar el CSV
df.to_csv(ruta_salida, index=False)

print("Archivo guardado en:")
print(ruta_salida)

Archivo guardado en:
C:\ProyectoIIMT\An-lisis-Sem-ntico-de-Rese-as-Tur-sticas-de-Costa-Rica-\data\processed\reseñas_clean_P2.csv